CPPFLAGS = -std=c++20 -pedantic-errors -Wall -Weffc++ -Wextra -Wconversion -Werror

# 4-10.o: 4-10.cpp 
#	g++ $(CPPFLAGS) -o 4-10 4-10.cpp

4-10q2.o: 4-10q2.cpp
	g++ $(CPPFLAGS) -o 4-10q2 4-10q2.cpp

clean:
	rm *.o output
