CPPFLAGS = -std=c++20 -pedantic-errors -Wall -Weffc++ -Wextra -Wconversion -Werror

2-xb.o: 2-xb.cpp 2-x_io.cpp
	g++ $(CPPFLAGS) -o 2-xb 2-xb.cpp 2-x_io.cpp

# 2-11.o: 2-11.cpp 2-11_add.cpp
#	g++ $(CPPFLAGS) -o 2-11 2-11.cpp 2-11_add.cpp

clean:
	rm *.o output
