CPPFLAGS = -std=c++20 -pedantic-errors -Wall -Weffc++ -Wextra -Wconversion -Werror

2-x.o: 2-x.cpp
	g++ $(CPPFLAGS) -o 2-x 2-x.cpp

# 2-8.o: 2-8c.cpp 2-8d.cpp
# 	g++ $(CPPFLAGS) -o 2-8 2-8c.cpp 2-8d.cpp

# 2-11.o: 2-11.cpp 2-11_add.cpp
#	g++ $(CPPFLAGS) -o 2-11 2-11.cpp 2-11_add.cpp

clean:
	rm *.o output
